---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24572.
--- DateTime: 2025/10/2 2:36
-- 比较线程标示与锁中的标示是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0